# Automatically closes the issue when the issue branch is merged
autoCloseIssue: true

# Placeholder: Skips creation of branch for issues with specified labels
#branches:
#  - label: my_label
#    skip: true

# Placeholder: Automatically open a (draft) Pull Request for the newly created branch. Enable this feature in your configuration YAML, for draft pull requests use:
#openDraftPR: true
#and for regular pull requests use:
openPR: true

# Placeholder: You can override the pull request target branch based on the issue label.
# For example, if you want (draft) pull requests for issues with the bug label to have the development branch as a source and have the pull request target branch set to hotfix, add this to your configuration YAML:
#branches:
#  - label: bug
#    name: development
#    prTarget: hotfix

# Placeholder: Automatically opening a (draft) PR for an issue requires an empty commit on the newly created branch (this is a requirement by GitHub). This first empty commit might trigger GitHub Actions CI workflows. You can skip these workflows with the following configuration option:
#prSkipCI: true
