@startuml
start
:Create Node HashSet //visited//;
:Create IObject HashMap //fn//;
:Create Optional Node //op//;
while(//op// Has a Value)
:Search //graph// for Happens 
Before Inverse Function;
:Set //op// to Visited //graph// Nodes;
endwhile
:Return //fn//;
stop
@enduml