@startuml
start
->File;
[[https://ontological-behavior-modeling.github.io/tester/edu/gatech/gtri/obm/translator/alloy/AlloyUtils.html#importAlloyModule(java.lang.String)]]:Import Alloy Module from File Path;
stop
@enduml