# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Javadocs

on:
  workflow_run:
   workflows: ["Release New Version"]
   types: [completed]
      
permissions:
  contents: write
  packages: write
  
jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The New Version has been Released
    
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          # git config --global url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/ # Use this line in private repo

      - name: Copy settings.xml
        run: cp ./.github/Maven/settings.xml $HOME/.m2/settings.xml

      - name: Prepare Version
        run: mvn versions:set -DremoveSnapshot

      - name: Setup Graphviz for UML in Javadocs
        uses: ts-graphviz/setup-graphviz@v2

      - name: Generate Javadocs
        run: mvn javadoc:javadoc
        env:
          GITHUB_TOKEN: ${{ secrets.JN_TOKEN }}

      - name: Deploy Javadocs to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./target/site/apidocs

      - name: Prepare Version
        run: mvn versions:revert
