name: Release New Package

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  packages: write

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: develop
        
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git config --global url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Copy settings.xml
        run: cp ./.github/Maven/settings.xml $HOME/.m2/settings.xml

      - name: Perform Maven Release
        run: |
          mvn release:perform -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.JN_TOKEN }}
