#Testing Differences between this and plantuml.yml
name: Push PlantUML Images

on:
  push:
    branches:
     'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:          
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Generate PlantUML
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: "."
          message: "Render PlantUML files"
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB.TOKEN }}
