# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Style Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Copy settings.xml
      run: cp ./.github/Maven/settings.xml $HOME/.m2/settings.xml

    - name: Check Spotless
      run: mvn spotless:check

    - name: Perform Maven Release
      run: |
        mvn release:perform -B
      env:
        GITHUB_TOKEN: ${{ secrets.JN_TOKEN }}
