name: Start Workflows

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        
    - name: Sleep for 45 seconds
      run: Start-Sleep -s 45
      shell: pwsh
